// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbooSdFm3yQ9C5ryLsfmvMNbTjWgvcKSE',
    appId: '1:497516535154:web:134d4eb5ccd551621111eb',
    messagingSenderId: '497516535154',
    projectId: 'fl-riverpod',
    authDomain: 'fl-riverpod.firebaseapp.com',
    storageBucket: 'fl-riverpod.appspot.com',
    measurementId: 'G-WHJSVS63BW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwmV9qcEoO57zwQXklEbXhnIJkMgg3zU',
    appId: '1:497516535154:ios:a8b7b6e37fec826e1111eb',
    messagingSenderId: '497516535154',
    projectId: 'fl-riverpod',
    storageBucket: 'fl-riverpod.appspot.com',
    androidClientId: '497516535154-pitmbivmjlgrov00smc9c6oemgc161cu.apps.googleusercontent.com',
    iosClientId: '497516535154-o9dfa3omlb4co01e91999p0qn1kmg2pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsdashboard.cmsDashboard.RunnerTests',
  );
}
